// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi-DxYPU4QkKGpLwMtBC8IuL--yELy3OY',
    appId: '1:727015250911:web:84ce2bac1edaf4d2d3826a',
    messagingSenderId: '727015250911',
    projectId: 'shop-together-ef908',
    authDomain: 'shop-together-ef908.firebaseapp.com',
    storageBucket: 'shop-together-ef908.firebasestorage.app',
    measurementId: 'G-JPNPLPC5ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-NHelZv4QarSiF2ZVs5N5GB57l8RaGvk',
    appId: '1:727015250911:android:145afc9de1f2d637d3826a',
    messagingSenderId: '727015250911',
    projectId: 'shop-together-ef908',
    storageBucket: 'shop-together-ef908.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQLqoX7oY5hlJXaZGbvFuASVBfUMJLl0U',
    appId: '1:727015250911:ios:18e6814a4bbd6929d3826a',
    messagingSenderId: '727015250911',
    projectId: 'shop-together-ef908',
    storageBucket: 'shop-together-ef908.firebasestorage.app',
    iosBundleId: 'com.example.shoptogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQLqoX7oY5hlJXaZGbvFuASVBfUMJLl0U',
    appId: '1:727015250911:ios:18e6814a4bbd6929d3826a',
    messagingSenderId: '727015250911',
    projectId: 'shop-together-ef908',
    storageBucket: 'shop-together-ef908.firebasestorage.app',
    iosBundleId: 'com.example.shoptogether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi-DxYPU4QkKGpLwMtBC8IuL--yELy3OY',
    appId: '1:727015250911:web:9396c2fbe4045199d3826a',
    messagingSenderId: '727015250911',
    projectId: 'shop-together-ef908',
    authDomain: 'shop-together-ef908.firebaseapp.com',
    storageBucket: 'shop-together-ef908.firebasestorage.app',
    measurementId: 'G-XTLB20021K',
  );
}
